### ISSUE TITLE
multiple upstreams with dynamic DNS lead to large metrics

### ISSUE THREAD

**Issue by bartjolenovation** [monitoring-tools/prom-nginx-exporter#10]
Hi we have an upstream section in our nginx conf defined with a consul address which can resolve to multiple instances of the app on the backend. These consul addresses are resolved round robin, so each time this address is resolved it creates a new instance within nginx. 
These instances are saved during the runtime of nginx and shown in the metrics page (which grew to > 15 MB).
It would be nice to be able to include excludes of certain upstream sections to prevent this.

**Comment by bartjolenovation** [comment]
As far as I can see it might be possible to skip upstreams in scraper/nginx_plus.go around line 122

**Comment by avthart** [comment]
You can could also remove the id label from the upstream_peer metrics because you get a new metric when the peer.id is changed as @bartjolenovation explained. The serverAddress should be enough to uniquely identify the correct peer/server.

The metrics page is growing because metrics are internally saved in a struct. Why do we need this? I am not interested in metrics that are not exposed anymore by nginx_status page.

**Comment by d-ulyanov** [comment]
@bartjolenovation thanks for this issue.

> I am not interested in metrics that are not exposed anymore by nginx_status page.

Definitely its a wrong behaviour, metrics should not grow and they should display only that we see on Nginx status page.

@vlamug Could you take a look this?

**Comment by vlamug** [comment]
@d-ulyanov yes, I am going to make change in the next few days. Thanks.

**Comment by d-ulyanov** [comment]
This PR: https://github.com/monitoring-tools/prom-nginx-exporter/pull/12
